### ISSUE TITLE
[ADO] potential v2.x breaking changes

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#1063]
This is a tracking issue with breaking changes that we would like to consider the next time we make an update to a new major version of the Azure DevOps extension.

* [x] Remove the Service Connection parameter (as part of dropping PR comment support) #1045 
* [x] Embed the "upload output artifact" step into the task, rather than requiring that the user add it separately #1085 
* [x] Options which users should rarely have to override should move to the bottom and be hidden by default under an "Advanced options" group which is collapsed by default. `chromePath` should go under here, and assuming we embed the "upload output artifact" step, so should `outputDir` #1092
* [x] `failOnAccessibilityError` should default to `true` instead of `false`
* [x] (see #1068) Modify the names/grouping of `siteDir`, `scanUrlRelativePath`, `localhostPort`, and `url` inputs to make it harder for users to accidentally configure mutually exclusive combinations of inputs #1122
    * Note: `inputFile`, `inputUrls`, and `discoveryPatterns` are *not* mutually exclusive with one another and should not be forced into separate groups like this. Their help text should be improved to clarify this, but improving their help text is non-breaking.

**Comment by karanbirsingh** [comment]
It seems experimentally that removing the service connection parameter is non-breaking; Tania explored this and found obsolete inputs are treated as warnings.
